### ISSUE TITLE
Third level domains

### ISSUE THREAD

**Issue by rhybmcc** [hacor/unifi-freeradius-ldap#16]
Our domain has 3 levels, eg. domain.com.com2.com3
The init.sh script only seems to support first and second level domains. After that, the base DN is incorrectly formatted in mods-available/ldap

It would be great to support 'infinite' number of levels, or request the base DN as a separate variable instead of automatically generating it from BASE_DOMAIN and DOMAIN_EXTENSION

**Comment by hacor** [comment]
@rhybmcc 
Very late response, sorry for that.
I understand your concern, but it is a bit out of the scope of this repo. I wrote it as a side project and I'm not using it actively anymore.
Always feel free to open a PR.

Thanks for using this repo

Warm regards

Hacor
