### ISSUE TITLE
radtest is failing 

### ISSUE THREAD

**Issue by avicoder** [hacor/unifi-freeradius-ldap#18]
Hi @hacor 

I have gone through the steps and follow each of them as mentioned, however after getting the message at the end 
```
Listening on auth address * port 1812 bound to server default
Listening on acct address * port 1813 bound to server default
Listening on auth address :: port 1812 bound to server default
Listening on acct address :: port 1813 bound to server default
Listening on auth address 127.0.0.1 port 18120 bound to server inner-tunnel
Listening on proxy address * port 59472
Listening on proxy address :: port 49558
Ready to process requests
```

I am not getting any confirmation that the connection with radius is established.

What am I doing wrong here?

**Comment by hacor** [comment]
@avicoder 
Your question is not completely clear to me. From the logs the container seems to launch perfectly. 
It is up to Unifi to connect to the radius server. And from that moment on you can start authenticating

**Comment by avicoder** [comment]
Sorry for not clarifying it well.

yeah the radius server is up and running however it is not reachable from neither localhost nor the whitelisted IP `ACCESS_ALLOWED_CIDR=192.168.10.0/24` 

I also tested it with `radtest` providing different ports such as `18210,1812,1813` but all failed to reach the docker.

 `radtest avicoder passwordtest localhost:1812 0 testing123`

receiving :
```
(0) No reply from server for ID 216 socket 5
```

**Comment by hacor** [comment]
It seems more like a network issue. Can you ping the host of the docker containers IP?

**Comment by avicoder** [comment]
Well i guess the issue was with the Docker Desktop for **Mac.** 
I spun a Debian 10 and follow the steps, it worked like charm.
