### ISSUE TITLE
How to access the logs?

### ISSUE THREAD

**Issue by avicoder** [hacor/unifi-freeradius-ldap#19]
Hello

Trying to resolve the problem of the RAIDUS server constantly hanging after a period of inactivity.

At this location :
`ls /var/log/freeradius
`
`radius.log  radwtmp
`

I checked the logs, but they appear empty.

Please let me know how to enable it, and check the logs.

**Comment by hacor** [comment]
All logs are routed to the container logs.
Uncomment `command: -X` in the docker compose file.

Please do read the README file
