### ISSUE TITLE
Raspberry Pi

### ISSUE THREAD

**Issue by Filippo1999** [hacor/unifi-freeradius-ldap#4]
Hi, when I make the compose up command (into Rasperry Pi 2 with latest Raspbian), I get "Exec format Error" at the command "RUN chmod +x /usr/local/bin/init.sh".
Googling I read that the fault is that this image isn't for Arm platform.
How can I resolve this?
In a Linux x64 is working so good, so thank you for your wonderful work!

**Comment by hacor** [comment]
Hi @Filippo1999 
Indeed ARM needs different builds. You need to start from a different ARM based [container](https://hub.docker.com/search?q=freeradius&type=image&architecture=arm%2Carm64). I have no further knowledge of ARM, and it could be possible that you need to rewrite the script a little bit to be compatible. But at first I would try to start from a ARM (64) supported FreeRadius image
All the best!
