### ISSUE TITLE
auth time

### ISSUE THREAD

**Issue by simllll** [hacor/unifi-freeradius-ldap#7]
Hi all,
thanks for this repo, it helped a lot,
I have some issues with too long auth requests though.

A mimimum request with radtest is 2 seconds, but sometimes it even fails due to too long requests from ldap (google). And 2 seconds is already kinda long for WPA2 auths, especially for roaming.

Do you have a similar experience? Is there any way to cache this more effectively? I was playing around with freeradius cache, and session cache already.. but so far no luck.

Thanks

**Comment by simllll** [comment]
btw:
It seems tuning pool option for ldap is doing the wrong thing and leads to failed auths.
I'm now with a pool size of min 0, max 1 and lowered all other settings in there.

**Comment by simllll** [comment]
setting ldap pool values to
start = 0
min = (min spare servers) => 1
max = (max servers) => 100
spare = 0 (or 1)
**uses = 10**
retry_delay = 1
lifetime = 100
idle_timeout = 5

reduces my average auth time from above 3 seconds to 1-2 seconds.

not sure how this is related though

**Comment by simllll** [comment]
seems like "uses: 0" does not mean "infinite".. but really to disconnect after each request, setting this value to 100 works perfectly fine and gives you a nice performance boost

**Comment by hacor** [comment]
Hi @simllll 
Glad you shared your experience here!
I'm closing this issue because it seems to work now. I'm taking your suggestion into account although I'm not having this problems in my environment.
