### ISSUE TITLE
standard_init_linux.go:211: exec user process caused "exec format error"

### ISSUE THREAD

**Issue by Piyaphong** [hacor/unifi-freeradius-ldap#8]
I found error
standard_init_linux.go:211: exec user process caused "exec format error"

when run with docker-compose on raspberrypi (Raspbian GNU/Linux 10)

**Comment by hacor** [comment]
Raspberry Pi needs a different build indeed (I think it's an ARM processor). So the packages need to be build from scratch which is not the main purpose of this repo.
